// Arquivo gerado automaticamente a partir dos exports em data/
// Fonte: data/meta-audiencia-mensal.xlsx, data/meta-mensagens-mensal.xlsx, data/instagram-organico-mensal.csv
// Edite via scripts/generate_creatives.py; não altere manualmente este arquivo.

export type CriativoCategoria = "audiencia" | "mensagens";
export type CriativoTipo = "reel" | "video" | "carrossel" | "imagem";

export type CriativoAmostra = "ok" | "baixa";

export interface CriativoBase {
  id: string;
  categoria: CriativoCategoria;
  nome: string;
  anuncio: string;
  campanha: string;
  tipo: CriativoTipo;
  periodo: string;
  inicioRelatorio: string;
  fimRelatorio: string;
  alcance: number;
  impressoes: number;
  cliquesLink: number;
  investido: number;
  ctr: number;
  cpc: number | null;
  influenciador: string | null;
  instagramUrl: string | null;
  instagramShortcode: string | null;
  thumbSrc: string | null;
}

export interface CriativoAudiencia extends CriativoBase {
  categoria: "audiencia";
  visitasPerfil: number;
  custoVisita: number | null;
}

export interface CriativoMensagens extends CriativoBase {
  categoria: "mensagens";
  conversas: number;
  custoConversa: number | null;
}

export const criativosAudienciaTodos = [
  {
    id: "aud-reels-layla-monteiro-10-08",
    categoria: "audiencia",
    nome: "Reels Layla Monteiro 10/08",
    anuncio: "Ad 2 - Reels Layla Monteiro 10/08",
    campanha: "[New Collection] [3] [Audiencia] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Layla",
    tipo: "reel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 24837,
    impressoes: 31401,
    cliquesLink: 2372,
    visitasPerfil: 2361,
    investido: 222.41,
    ctr: 7.55,
    cpc: 0.09,
    custoVisita: 0.09,
    influenciador: "Layla Monteiro",
    instagramUrl: "https://www.instagram.com/reel/DNMFXAVsxnM/",
    instagramShortcode: "DNMFXAVsxnM",
    thumbSrc: "/ads/mm-ig-DNMFXAVsxnM.jpg",
  },
  {
    id: "aud-reels-20-06",
    categoria: "audiencia",
    nome: "Reels 20/06",
    anuncio: "Ad 0 - Reels 20/06",
    campanha: "[Geral] [Junho] [Post. Ka Branquinho] [Audiencia] [Trafego -> View Ig perfil] [Frio - Gyn/Sud] - Reels 21/06",
    tipo: "reel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 4891,
    impressoes: 6134,
    cliquesLink: 460,
    visitasPerfil: 469,
    investido: 124.67,
    ctr: 7.5,
    cpc: 0.27,
    custoVisita: 0.27,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "aud-video-post-28-11",
    categoria: "audiencia",
    nome: "Vídeo Post 28/11",
    anuncio: "Ad 0 - Vídeo Post 28/11",
    campanha: "[Origem] [Audiencia] [Post 28/11] [Trafego -> View Ig] [Frio] [IG] - Postagem Isadora Reels IG",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 3132,
    impressoes: 3664,
    cliquesLink: 239,
    visitasPerfil: 237,
    investido: 50.97,
    ctr: 6.52,
    cpc: 0.21,
    custoVisita: 0.22,
    influenciador: "Isadora",
    instagramUrl: "https://www.instagram.com/reel/DRnYRlxD7k3/",
    instagramShortcode: "DRnYRlxD7k3",
    thumbSrc: "/ads/mm-ig-DRnYRlxD7k3.jpg",
  },
  {
    id: "aud-video-post-04-12",
    categoria: "audiencia",
    nome: "Vídeo Post 04/12",
    anuncio: "Ad 0 - Vídeo Post 04/12",
    campanha: "[Colecao AURA] [Audiencia] [Post 04/12] [Trafego -> View Ig] [Frio] [IG] - Postagem Isadora Reels IG",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 21653,
    impressoes: 29256,
    cliquesLink: 1825,
    visitasPerfil: 1802,
    investido: 320.56,
    ctr: 6.24,
    cpc: 0.18,
    custoVisita: 0.18,
    influenciador: "Isadora",
    instagramUrl: "https://www.instagram.com/reel/DR2IGyCDapj/",
    instagramShortcode: "DR2IGyCDapj",
    thumbSrc: "/ads/mm-ig-DR2IGyCDapj.jpg",
  },
  {
    id: "aud-video-post-12-11",
    categoria: "audiencia",
    nome: "Vídeo Post 12/11",
    anuncio: "Ad 0 - Vídeo Post 12/11",
    campanha: "[New Collection] [Audiencia] [4] [Post 12/11] [Trafego -> View Ig] [Frio] [IG] - POSTAGENS IG",
    tipo: "video",
    periodo: "Nov–Dez/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-12-26",
    alcance: 2282,
    impressoes: 2490,
    cliquesLink: 145,
    visitasPerfil: 160,
    investido: 59.89,
    ctr: 5.82,
    cpc: 0.41,
    custoVisita: 0.37,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DQ9dJg3jw2b/",
    instagramShortcode: "DQ9dJg3jw2b",
    thumbSrc: "/ads/mm-ig-DQ9dJg3jw2b.jpg",
  },
  {
    id: "aud-reels-isadora-04-09",
    categoria: "audiencia",
    nome: "Reels Isadora 04/09",
    anuncio: "Ad 0 - Reels Isadora 04/09",
    campanha: "[Audiencia] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Isadora 04-09",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 8054,
    impressoes: 8476,
    cliquesLink: 444,
    visitasPerfil: 441,
    investido: 118.22,
    ctr: 5.24,
    cpc: 0.27,
    custoVisita: 0.27,
    influenciador: "Isadora",
    instagramUrl: "https://www.instagram.com/reel/DOMrkW3js5f/",
    instagramShortcode: "DOMrkW3js5f",
    thumbSrc: "/ads/mm-ig-DOMrkW3js5f.jpg",
  },
  {
    id: "aud-reels-colecao-primavera-15-08",
    categoria: "audiencia",
    nome: "Reels Coleçao Primavera [15/08]",
    anuncio: "Ad 0 - Reels Coleçao Primavera [15/08]",
    campanha: "[New Collection] [Audiencia] [Trafego -> View Ig] [Frio] [St/Reels] - Reels 15/08 Nova Colecao",
    tipo: "reel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 11042,
    impressoes: 12549,
    cliquesLink: 627,
    visitasPerfil: 663,
    investido: 222.68,
    ctr: 5,
    cpc: 0.36,
    custoVisita: 0.34,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DNYSvz6OZ4D/",
    instagramShortcode: "DNYSvz6OZ4D",
    thumbSrc: "/ads/mm-ig-DNYSvz6OZ4D.jpg",
  },
  {
    id: "aud-video-post-21-11",
    categoria: "audiencia",
    nome: "Vídeo Post 21/11",
    anuncio: "Ad 0 - Vídeo Post 21/11",
    campanha: "[Origem] [Audiencia] [Post 22/11] [Trafego -> View Ig] [Frio] [IG] - POSTAGENS IG",
    tipo: "video",
    periodo: "Nov–Dez/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-12-26",
    alcance: 11923,
    impressoes: 13578,
    cliquesLink: 644,
    visitasPerfil: 654,
    investido: 228.28,
    ctr: 4.74,
    cpc: 0.35,
    custoVisita: 0.35,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DRacw8kDxgq/",
    instagramShortcode: "DRacw8kDxgq",
    thumbSrc: "/ads/mm-ig-DRacw8kDxgq.jpg",
  },
  {
    id: "aud-post-reels-04-10",
    categoria: "audiencia",
    nome: "Post Reels 04/10",
    anuncio: "Ad 0 - Post Reels 04/10",
    campanha: "[Audiencia] [Out/25] [3] [Trafego -> View Ig] [Frio] [IG] - Reels Post",
    tipo: "reel",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 31026,
    impressoes: 43090,
    cliquesLink: 2041,
    visitasPerfil: 2034,
    investido: 410.62,
    ctr: 4.74,
    cpc: 0.2,
    custoVisita: 0.2,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DPZiAbfjeSN/",
    instagramShortcode: "DPZiAbfjeSN",
    thumbSrc: "/ads/mm-ig-DPZiAbfjeSN.jpg",
  },
  {
    id: "aud-video-post-24-11",
    categoria: "audiencia",
    nome: "Vídeo Post 24/11",
    anuncio: "Ad 0 - Vídeo Post 24/11",
    campanha: "[Origem] [Audiencia] [Post 24/11] [Trafego -> View Ig] [Frio] [IG] - POSTAGENS IG",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 2236,
    impressoes: 2810,
    cliquesLink: 125,
    visitasPerfil: 139,
    investido: 51.63,
    ctr: 4.45,
    cpc: 0.41,
    custoVisita: 0.37,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DRdL4w3jxSs/",
    instagramShortcode: "DRdL4w3jxSs",
    thumbSrc: "/ads/mm-ig-DRdL4w3jxSs.jpg",
  },
  {
    id: "aud-video-post-26-11",
    categoria: "audiencia",
    nome: "Vídeo Post 26/11",
    anuncio: "Ad 0 - Vídeo Post 26/11",
    campanha: "[Thassia] [Audiencia] [Trafego -> View Ig] [Frio] [IG] - Video Reels Thassia",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 21315,
    impressoes: 29399,
    cliquesLink: 1306,
    visitasPerfil: 1378,
    investido: 379.76,
    ctr: 4.44,
    cpc: 0.29,
    custoVisita: 0.28,
    influenciador: "Thassia",
    instagramUrl: "https://www.instagram.com/reel/DRk6URAj34p/",
    instagramShortcode: "DRk6URAj34p",
    thumbSrc: "/ads/mm-ig-DRk6URAj34p.jpg",
  },
  {
    id: "aud-video-post-16-12",
    categoria: "audiencia",
    nome: "Vídeo Post 16/12",
    anuncio: "Ad 0 - Vídeo Post 16/12",
    campanha: "[Geral] [3] [Audiencia] [Trafego -> View Ig] [Frio] [IG] - Video Reels IG",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 7980,
    impressoes: 9843,
    cliquesLink: 413,
    visitasPerfil: 418,
    investido: 90.83,
    ctr: 4.2,
    cpc: 0.22,
    custoVisita: 0.22,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DSV1Y7RD80e/",
    instagramShortcode: "DSV1Y7RD80e",
    thumbSrc: "/ads/mm-ig-DSV1Y7RD80e.jpg",
  },
  {
    id: "aud-video-post-19-11",
    categoria: "audiencia",
    nome: "Vídeo Post 19/11",
    anuncio: "Ad 0 - Vídeo Post 19/11",
    campanha: "[Origem] [Audiencia] [Post 19/11] [Trafego -> View Ig] [Frio] [IG] - POSTAGENS IG — Cópia",
    tipo: "video",
    periodo: "Nov–Dez/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-12-26",
    alcance: 12337,
    impressoes: 14185,
    cliquesLink: 594,
    visitasPerfil: 585,
    investido: 198.44,
    ctr: 4.19,
    cpc: 0.33,
    custoVisita: 0.34,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DRNvHL1CQxO/",
    instagramShortcode: "DRNvHL1CQxO",
    thumbSrc: "/ads/mm-ig-DRNvHL1CQxO.jpg",
  },
  {
    id: "aud-video-post-11-11",
    categoria: "audiencia",
    nome: "Vídeo Post 11/11",
    anuncio: "Ad 0 - Vídeo Post 11/11",
    campanha: "[New Collection] [Audiencia] [3] [Post 11/11] [Trafego -> View Ig] [Frio] [IG] - POSTAGENS IG",
    tipo: "video",
    periodo: "Nov–Dez/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-12-26",
    alcance: 2929,
    impressoes: 3296,
    cliquesLink: 131,
    visitasPerfil: 139,
    investido: 59.8,
    ctr: 3.97,
    cpc: 0.46,
    custoVisita: 0.43,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DQ7tmgpjxZy/",
    instagramShortcode: "DQ7tmgpjxZy",
    thumbSrc: "/ads/mm-ig-DQ7tmgpjxZy.jpg",
  },
  {
    id: "aud-reels-11-08",
    categoria: "audiencia",
    nome: "Reels 11/08",
    anuncio: "Ad 2 - Reels 11/08",
    campanha: "[New Collection] [2] [Audiencia] [Trafego -> View Ig] [Frio] [St/Reels] - Reels 11/08",
    tipo: "reel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 13799,
    impressoes: 15788,
    cliquesLink: 566,
    visitasPerfil: 571,
    investido: 227.6,
    ctr: 3.59,
    cpc: 0.4,
    custoVisita: 0.4,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DNO0aOvP7IF/",
    instagramShortcode: "DNO0aOvP7IF",
    thumbSrc: "/ads/mm-ig-DNO0aOvP7IF.jpg",
  },
  {
    id: "aud-carrossel-post-31-07",
    categoria: "audiencia",
    nome: "Carrossel Post 31/07",
    anuncio: "Ad 0 - Carrossel Post 31/07",
    campanha: "[Monica Metran] [Audiencia] [Trafego -> Ig] [Pub. Frio] [St] - Carrossel Post",
    tipo: "carrossel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 1732,
    impressoes: 2164,
    cliquesLink: 77,
    visitasPerfil: 83,
    investido: 33.85,
    ctr: 3.56,
    cpc: 0.44,
    custoVisita: 0.41,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DMyfsmuMDm-/",
    instagramShortcode: "DMyfsmuMDm-",
    thumbSrc: "/ads/mm-ig-DMyfsmuMDm-.jpg",
  },
  {
    id: "aud-reels-20-09",
    categoria: "audiencia",
    nome: "Reels  20/09",
    anuncio: "Ad 0 - Reels  20/09",
    campanha: "[Audiencia] [3] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Post 20/09",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 15946,
    impressoes: 19326,
    cliquesLink: 676,
    visitasPerfil: 663,
    investido: 307.56,
    ctr: 3.5,
    cpc: 0.45,
    custoVisita: 0.46,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DO1AD-FjRPw/",
    instagramShortcode: "DO1AD-FjRPw",
    thumbSrc: "/ads/mm-ig-DO1AD-FjRPw.jpg",
  },
  {
    id: "aud-reels-21-09",
    categoria: "audiencia",
    nome: "Reels  21/09",
    anuncio: "Ad 0 - Reels  21/09",
    campanha: "[Audiencia] [4] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Post 21/09",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 22187,
    impressoes: 27325,
    cliquesLink: 914,
    visitasPerfil: 871,
    investido: 304.15,
    ctr: 3.34,
    cpc: 0.33,
    custoVisita: 0.35,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DO4Yyh1DVp-/",
    instagramShortcode: "DO4Yyh1DVp-",
    thumbSrc: "/ads/mm-ig-DO4Yyh1DVp-.jpg",
  },
  {
    id: "aud-reels-isadora-08-07",
    categoria: "audiencia",
    nome: "Reels Isadora 08/07",
    anuncio: "Ad 0 - Reels Isadora 08/07",
    campanha: "[Geral - Julho] [St/Reels] [Audiencia] [Trafego -> View Ig perfil] [Frio - Gyn/Sud] - Reels 08/07",
    tipo: "reel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 11111,
    impressoes: 14797,
    cliquesLink: 493,
    visitasPerfil: 516,
    investido: 174.9,
    ctr: 3.33,
    cpc: 0.35,
    custoVisita: 0.34,
    influenciador: "Isadora",
    instagramUrl: "https://www.instagram.com/reel/DL3WNyet3vN/",
    instagramShortcode: "DL3WNyet3vN",
    thumbSrc: "/ads/mm-ig-DL3WNyet3vN.jpg",
  },
  {
    id: "aud-cards-videos-feed",
    categoria: "audiencia",
    nome: "Cards + Videos (feed)",
    anuncio: "Ad 0 - Cards + Videos (feed)",
    campanha: "[New Collection] [Audiencia] [Rmkt] [Trafego -> Visitas ao Perfil] - Cards + Videos",
    tipo: "video",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 2053,
    impressoes: 2533,
    cliquesLink: 81,
    visitasPerfil: 98,
    investido: 45.7,
    ctr: 3.2,
    cpc: 0.56,
    custoVisita: 0.47,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "aud-post-reels-02-11",
    categoria: "audiencia",
    nome: "Post Reels 02/11",
    anuncio: "Ad 0 - Post Reels 02/11",
    campanha: "[New Collection] [Audiencia] [Nov/25] [Trafego -> View Ig] [Frio] [IG] - Reels Post 03/11",
    tipo: "reel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 21556,
    impressoes: 26519,
    cliquesLink: 826,
    visitasPerfil: 845,
    investido: 452.85,
    ctr: 3.11,
    cpc: 0.55,
    custoVisita: 0.54,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DQkegXhDUks/",
    instagramShortcode: "DQkegXhDUks",
    thumbSrc: "/ads/mm-ig-DQkegXhDUks.jpg",
  },
  {
    id: "aud-carrossel-feed-04-07",
    categoria: "audiencia",
    nome: "Carrossel Feed 04/07",
    anuncio: "Ad 0 - Carrossel Feed 04/07",
    campanha: "[Geral - Julho] [Feed] [Audiencia] [Trafego -> View Ig perfil] [Frio - Gyn/Sud] - Carrossel 04/07",
    tipo: "carrossel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 15042,
    impressoes: 24199,
    cliquesLink: 750,
    visitasPerfil: 837,
    investido: 364.45,
    ctr: 3.1,
    cpc: 0.49,
    custoVisita: 0.44,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DLs3WSwMRWy/",
    instagramShortcode: "DLs3WSwMRWy",
    thumbSrc: "/ads/mm-ig-DLs3WSwMRWy.jpg",
  },
  {
    id: "aud-carrossel-post-ig",
    categoria: "audiencia",
    nome: "Carrossel Post IG",
    anuncio: "Ad 0 - Carrossel Post IG",
    campanha: "[Cristal Lobo] [Audiencia] [Trafego -> Ig] [Pub. Frio] [St] - Carrossel Post",
    tipo: "carrossel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 9542,
    impressoes: 11727,
    cliquesLink: 356,
    visitasPerfil: 382,
    investido: 137.76,
    ctr: 3.04,
    cpc: 0.39,
    custoVisita: 0.36,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "aud-carrossel-feed-12-07-cristal-lobo",
    categoria: "audiencia",
    nome: "Carrossel Feed 12/07 (cristal lobo)",
    anuncio: "Ad 0 - Carrossel Feed 12/07 (cristal lobo)",
    campanha: "[Geral - Julho] [Feed] [2] [Audiencia] [Trafego -> View Ig perfil] [Frio - Gyn/Sud] - Carrossel 12/07",
    tipo: "carrossel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 10505,
    impressoes: 13768,
    cliquesLink: 419,
    visitasPerfil: 433,
    investido: 174.21,
    ctr: 3.04,
    cpc: 0.42,
    custoVisita: 0.4,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DMA-y07srm5/",
    instagramShortcode: "DMA-y07srm5",
    thumbSrc: "/ads/mm-ig-DMA-y07srm5.jpg",
  },
  {
    id: "aud-post-reels-13-10",
    categoria: "audiencia",
    nome: "Post Reels 13/10",
    anuncio: "Ad 6 - Post Reels 13/10",
    campanha: "[Audiencia] [Out/25] [6] [Trafego -> View Ig] [Frio] [IG] - Reels Post 13/10",
    tipo: "reel",
    periodo: "Out–Nov/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-11-30",
    alcance: 9972,
    impressoes: 12030,
    cliquesLink: 360,
    visitasPerfil: 394,
    investido: 142.74,
    ctr: 2.99,
    cpc: 0.4,
    custoVisita: 0.36,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DPxFoleDbKl/",
    instagramShortcode: "DPxFoleDbKl",
    thumbSrc: "/ads/mm-ig-DPxFoleDbKl.jpg",
  },
  {
    id: "aud-cards-videos-st",
    categoria: "audiencia",
    nome: "Cards + Videos (St)",
    anuncio: "Ad 0 - Cards + Videos (St)",
    campanha: "[New Collection] [Audiencia] [Rmkt] [Trafego -> Visitas ao Perfil] - Cards + Videos",
    tipo: "video",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 2731,
    impressoes: 4201,
    cliquesLink: 125,
    visitasPerfil: 132,
    investido: 43.99,
    ctr: 2.98,
    cpc: 0.35,
    custoVisita: 0.33,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "aud-reels-12-09",
    categoria: "audiencia",
    nome: "Reels  12/09",
    anuncio: "Ad 0 - Reels  12/09",
    campanha: "[Audiencia] [1] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Post 12/09",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 19223,
    impressoes: 23077,
    cliquesLink: 668,
    visitasPerfil: 639,
    investido: 304.32,
    ctr: 2.89,
    cpc: 0.46,
    custoVisita: 0.48,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DOhJN0UjeIL/",
    instagramShortcode: "DOhJN0UjeIL",
    thumbSrc: "/ads/mm-ig-DOhJN0UjeIL.jpg",
  },
  {
    id: "aud-reels-isadora-15-08",
    categoria: "audiencia",
    nome: "Reels Isadora [15/08]",
    anuncio: "Ad 1 - Reels Isadora [15/08]",
    campanha: "[Institucional] [2] [Audiencia] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Isadora Institucional",
    tipo: "reel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 14833,
    impressoes: 17236,
    cliquesLink: 481,
    visitasPerfil: 497,
    investido: 222.94,
    ctr: 2.79,
    cpc: 0.46,
    custoVisita: 0.45,
    influenciador: "Isadora",
    instagramUrl: "https://www.instagram.com/reel/DNYSvz6OZ4D/",
    instagramShortcode: "DNYSvz6OZ4D",
    thumbSrc: "/ads/mm-ig-DNYSvz6OZ4D.jpg",
  },
  {
    id: "aud-post-reels-24-10",
    categoria: "audiencia",
    nome: "Post Reels 24/10",
    anuncio: "Ad 4 - Post Reels 24/10",
    campanha: "[Audiencia] [Out/25] [4] [Trafego -> View Ig] [Frio] [IG] - Reels Post 24/10",
    tipo: "reel",
    periodo: "Out–Nov/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-11-30",
    alcance: 9388,
    impressoes: 10512,
    cliquesLink: 291,
    visitasPerfil: 297,
    investido: 143.8,
    ctr: 2.77,
    cpc: 0.49,
    custoVisita: 0.48,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DQNQbbtjw4R/",
    instagramShortcode: "DQNQbbtjw4R",
    thumbSrc: "/ads/mm-ig-DQNQbbtjw4R.jpg",
  },
  {
    id: "aud-video-post-18-12",
    categoria: "audiencia",
    nome: "Vídeo Post 18/12",
    anuncio: "Ad 0 - Vídeo Post 18/12",
    campanha: "[Geral] [Audiencia] [Trafego -> View Ig] [Frio] [IG] - Video Reels IG",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 9216,
    impressoes: 11766,
    cliquesLink: 320,
    visitasPerfil: 364,
    investido: 91,
    ctr: 2.72,
    cpc: 0.28,
    custoVisita: 0.25,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DSa_BQ5j5mh/",
    instagramShortcode: "DSa_BQ5j5mh",
    thumbSrc: "/ads/mm-ig-DSa_BQ5j5mh.jpg",
  },
  {
    id: "aud-reels-07-07-alianca",
    categoria: "audiencia",
    nome: "Reels 07/07 (Aliança)",
    anuncio: "Ad 0 - Reels 07/07 (Aliança)",
    campanha: "[Geral - Julho] [St/Reels] [2] [Audiencia] [Trafego -> View Ig perfil] [Frio - Gyn/Sud] - Reels 07/07",
    tipo: "reel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 12640,
    impressoes: 14779,
    cliquesLink: 396,
    visitasPerfil: 416,
    investido: 171.38,
    ctr: 2.68,
    cpc: 0.43,
    custoVisita: 0.41,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DL0smKRB0uS/",
    instagramShortcode: "DL0smKRB0uS",
    thumbSrc: "/ads/mm-ig-DL0smKRB0uS.jpg",
  },
  {
    id: "aud-post-reels-18-10",
    categoria: "audiencia",
    nome: "Post Reels 18/10",
    anuncio: "Ad 5 - Post Reels 18/10",
    campanha: "[Audiencia] [Out/25] [5] [Trafego -> View Ig] [Frio] [IG] - Reels Post 18/10",
    tipo: "reel",
    periodo: "Out–Nov/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-11-30",
    alcance: 11021,
    impressoes: 13251,
    cliquesLink: 351,
    visitasPerfil: 385,
    investido: 142.45,
    ctr: 2.65,
    cpc: 0.41,
    custoVisita: 0.37,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DP9UvzcD2fQ/",
    instagramShortcode: "DP9UvzcD2fQ",
    thumbSrc: "/ads/mm-ig-DP9UvzcD2fQ.jpg",
  },
  {
    id: "aud-reels-18-09",
    categoria: "audiencia",
    nome: "Reels  18/09",
    anuncio: "Ad 0 - Reels  18/09",
    campanha: "[Audiencia] [2] [Trafego -> View Ig] [Frio] [St/Reels] - Reels Post 18/09",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 19713,
    impressoes: 23355,
    cliquesLink: 609,
    visitasPerfil: 574,
    investido: 307.76,
    ctr: 2.61,
    cpc: 0.51,
    custoVisita: 0.54,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DOwx3E3Ddrz/",
    instagramShortcode: "DOwx3E3Ddrz",
    thumbSrc: "/ads/mm-ig-DOwx3E3Ddrz.jpg",
  },
  {
    id: "aud-carrossel-feed-04-11",
    categoria: "audiencia",
    nome: "Carrossel Feed 04/11",
    anuncio: "Ad 0 - Carrossel Feed 04/11",
    campanha: "[New Collection] [Audiencia] [2] [Nov/25] [Trafego -> View Ig] [Frio] [Feed] - Post Feed 04/11",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 25960,
    impressoes: 30106,
    cliquesLink: 731,
    visitasPerfil: 729,
    investido: 378.37,
    ctr: 2.43,
    cpc: 0.52,
    custoVisita: 0.52,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DQpvfRoDw48/",
    instagramShortcode: "DQpvfRoDw48",
    thumbSrc: "/ads/mm-ig-DQpvfRoDw48.jpg",
  },
  {
    id: "aud-post-fd-29-10",
    categoria: "audiencia",
    nome: "Post Fd 29/10",
    anuncio: "Ad 0 - Post Fd 29/10",
    campanha: "[Audiencia] [Out/25] [2] [Trafego -> View Ig] [Frio] [IG] - Reels Post",
    tipo: "imagem",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 44918,
    impressoes: 62256,
    cliquesLink: 1494,
    visitasPerfil: 1514,
    investido: 522.29,
    ctr: 2.4,
    cpc: 0.35,
    custoVisita: 0.34,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DQaS3weDiHS/",
    instagramShortcode: "DQaS3weDiHS",
    thumbSrc: "/ads/mm-ig-DQaS3weDiHS.jpg",
  },
  {
    id: "aud-video-colecao-origem",
    categoria: "audiencia",
    nome: "Vídeo Coleção Origem",
    anuncio: "Ad 0 - Vídeo Coleção Origem",
    campanha: "[New Collection] [Audiencia] [3] [Nov/25] [Trafego -> View Ig] [Frio] [IG] - Vídeo Coleção",
    tipo: "video",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 13541,
    impressoes: 14864,
    cliquesLink: 343,
    visitasPerfil: 359,
    investido: 183.51,
    ctr: 2.31,
    cpc: 0.54,
    custoVisita: 0.51,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "aud-carrossel-post-ig-04-08",
    categoria: "audiencia",
    nome: "Carrossel Post IG 04/08",
    anuncio: "Ad 0 - Carrossel Post IG 04/08",
    campanha: "[Ana Rassi] [Audiencia] [Trafego -> Ig] [Pub. Frio] [Feed] - Carrossel Post 04/08",
    tipo: "carrossel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 27532,
    impressoes: 35550,
    cliquesLink: 767,
    visitasPerfil: 816,
    investido: 362.29,
    ctr: 2.16,
    cpc: 0.47,
    custoVisita: 0.44,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DM8r-QTvfka/",
    instagramShortcode: "DM8r-QTvfka",
    thumbSrc: "/ads/mm-ig-DM8r-QTvfka.jpg",
  },
  {
    id: "aud-post-fd-25-10",
    categoria: "audiencia",
    nome: "Post Fd 25/10",
    anuncio: "Ad 0 - Post Fd 25/10",
    campanha: "[Audiencia] [Out/25] [Trafego -> View Ig] [Frio] [IG] - Reels Post",
    tipo: "imagem",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 41853,
    impressoes: 60776,
    cliquesLink: 1221,
    visitasPerfil: 1290,
    investido: 525.22,
    ctr: 2.01,
    cpc: 0.43,
    custoVisita: 0.41,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DQSWjd1D6WY/",
    instagramShortcode: "DQSWjd1D6WY",
    thumbSrc: "/ads/mm-ig-DQSWjd1D6WY.jpg",
  },
  {
    id: "aud-carrossel-stories",
    categoria: "audiencia",
    nome: "Carrossel Stories",
    anuncio: "Ad 1 - Carrossel Stories",
    campanha: "[Escapulario] [H/M] [Audiencia] [Trafego -> View Ig perfil] [Frio] [Stories] - Stories",
    tipo: "carrossel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 20737,
    impressoes: 32570,
    cliquesLink: 606,
    visitasPerfil: 647,
    investido: 239.46,
    ctr: 1.86,
    cpc: 0.4,
    custoVisita: 0.37,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "aud-carrossel-06-07",
    categoria: "audiencia",
    nome: "Carrossel 06/07",
    anuncio: "Ad 0 - Carrossel 06/07",
    campanha: "[Escapulario p/ homens] [H/M] [Audiencia] [Trafego -> View Ig perfil] [Frio] - Vídeos",
    tipo: "carrossel",
    periodo: "Jul/2025",
    inicioRelatorio: "2025-07-01",
    fimRelatorio: "2025-07-31",
    alcance: 16159,
    impressoes: 23319,
    cliquesLink: 381,
    visitasPerfil: 378,
    investido: 241.56,
    ctr: 1.63,
    cpc: 0.63,
    custoVisita: 0.64,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DLx9gsgPNsv/",
    instagramShortcode: "DLx9gsgPNsv",
    thumbSrc: "/ads/mm-ig-DLx9gsgPNsv.jpg",
  },
  {
    id: "aud-video-post-17-12",
    categoria: "audiencia",
    nome: "Vídeo Post 17/12",
    anuncio: "Ad 0 - Vídeo Post 17/12",
    campanha: "[Geral] [2] [Audiencia] [Trafego -> View Ig] [Frio] [IG] - Video Reels IG",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 9615,
    impressoes: 15278,
    cliquesLink: 117,
    visitasPerfil: 129,
    investido: 45.24,
    ctr: 0.77,
    cpc: 0.39,
    custoVisita: 0.35,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DSYbP3xjdkV/",
    instagramShortcode: "DSYbP3xjdkV",
    thumbSrc: "/ads/mm-ig-DSYbP3xjdkV.jpg",
  },
  {
    id: "aud-video-post-17-11",
    categoria: "audiencia",
    nome: "Vídeo Post 17/11",
    anuncio: "Ad 0 - Vídeo Post 17/11",
    campanha: "[Nova Loja] [2] [Audiencia]  [Trafego -> View Ig] [Goiania] [IG] - Post Loja",
    tipo: "video",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 5,
    impressoes: 5,
    cliquesLink: 0,
    visitasPerfil: 0,
    investido: 0.04,
    ctr: 0,
    cpc: null,
    custoVisita: null,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DRLOBPADR_L/",
    instagramShortcode: "DRLOBPADR_L",
    thumbSrc: "/ads/mm-ig-DRLOBPADR_L.jpg",
  },
] as const;

export const criativosMensagensTodos = [
  {
    id: "msg-carrossel-origem-post-nos-stories",
    categoria: "mensagens",
    nome: "Carrossel Origem (post nos stories)",
    anuncio: "Ad 0 - Carrossel Origem (post nos stories)",
    campanha: "[New Collection] [Msg] [Rmkt] [2] [Engaj. -> Wpp] [Cbo] [St] - Carrossel St",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 340,
    impressoes: 379,
    cliquesLink: 5,
    conversas: 3,
    investido: 9.41,
    ctr: 1.32,
    cpc: 1.88,
    custoConversa: 3.14,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-colecao-aura",
    categoria: "mensagens",
    nome: "Video colecao aura",
    anuncio: "Ad 0 - Video colecao aura",
    campanha: "[Msg] [Colecao AURA] [4] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Videos",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 1491,
    impressoes: 1971,
    cliquesLink: 41,
    conversas: 10,
    investido: 33.84,
    ctr: 2.08,
    cpc: 0.83,
    custoConversa: 3.38,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-colecao-aura-2",
    categoria: "mensagens",
    nome: "Video colecao aura [2]",
    anuncio: "Ad 1 - Video colecao aura [2]",
    campanha: "[Msg] [Colecao AURA] [4] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Videos",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 4241,
    impressoes: 7450,
    cliquesLink: 141,
    conversas: 27,
    investido: 125.86,
    ctr: 1.89,
    cpc: 0.89,
    custoConversa: 4.66,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-mm-diamonds-edicao-especial-2",
    categoria: "mensagens",
    nome: "Vídeo MM Diamonds - Edicao Especial [2]",
    anuncio: "Ad 5 - Vídeo MM Diamonds - Edicao Especial [2]",
    campanha: "[Msg] [Especial Presentes] [2] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Vídeos",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 803,
    impressoes: 942,
    cliquesLink: 7,
    conversas: 3,
    investido: 14.2,
    ctr: 0.74,
    cpc: 2.03,
    custoConversa: 4.73,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-colecao-aura",
    categoria: "mensagens",
    nome: "Carrossel colecao aura",
    anuncio: "Ad 2 - Carrossel colecao aura",
    campanha: "[Msg] [Colecao AURA] [3] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 6921,
    impressoes: 25944,
    cliquesLink: 383,
    conversas: 86,
    investido: 640.82,
    ctr: 1.48,
    cpc: 1.67,
    custoConversa: 7.45,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-colecao-aura-2",
    categoria: "mensagens",
    nome: "Video Colecao Aura [2]",
    anuncio: "Ad 1 - Video Colecao Aura [2]",
    campanha: "[Msg] [Colecao AURA] [2] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Videos diversos — Cópia",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 4345,
    impressoes: 9330,
    cliquesLink: 145,
    conversas: 29,
    investido: 297.12,
    ctr: 1.55,
    cpc: 2.05,
    custoConversa: 10.25,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-new-collection-shop-now",
    categoria: "mensagens",
    nome: "Carrossel New Collection \"shop now\"",
    anuncio: "Ad 0 - Carrossel New Collection \"shop now\"",
    campanha: "[Msg] [New Collection] [Rmkt All] [Engaj. -> Conversas Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 3001,
    impressoes: 7991,
    cliquesLink: 109,
    conversas: 34,
    investido: 431.24,
    ctr: 1.36,
    cpc: 3.96,
    custoConversa: 12.68,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-post-reels-isadora",
    categoria: "mensagens",
    nome: "Post Reels Isadora",
    anuncio: "Ad 2 - Post Reels Isadora",
    campanha: "[Msg] [Frio] [Engaj. -> Wpp] [Cbo] - Video",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 4154,
    impressoes: 5034,
    cliquesLink: 71,
    conversas: 20,
    investido: 283.95,
    ctr: 1.41,
    cpc: 4,
    custoConversa: 14.2,
    influenciador: "Isadora",
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-feed-03-09-mm-diamond",
    categoria: "mensagens",
    nome: "Carrossel Feed 03/09 (MM Diamond)",
    anuncio: "Ad 2 - Carrossel Feed 03/09 (MM Diamond)",
    campanha: "[Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 6645,
    impressoes: 11534,
    cliquesLink: 130,
    conversas: 23,
    investido: 338.1,
    ctr: 1.13,
    cpc: 2.6,
    custoConversa: 14.7,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DOHXrCUj4e_/",
    instagramShortcode: "DOHXrCUj4e_",
    thumbSrc: "/ads/mm-ig-DOHXrCUj4e_.jpg",
  },
  {
    id: "msg-post-reels-evento-aurora-04-09",
    categoria: "mensagens",
    nome: "Post Reels Evento Aurora (04/09)",
    anuncio: "Ad 1 - Post Reels Evento Aurora (04/09)",
    campanha: "[Msg] [Frio] [Engaj. -> Wpp] [Cbo] - Video",
    tipo: "reel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 5642,
    impressoes: 7227,
    cliquesLink: 91,
    conversas: 25,
    investido: 382.04,
    ctr: 1.26,
    cpc: 4.2,
    custoConversa: 15.28,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DOMrkW3js5f/",
    instagramShortcode: "DOMrkW3js5f",
    thumbSrc: "/ads/mm-ig-DOMrkW3js5f.jpg",
  },
  {
    id: "msg-video-colecao-aura",
    categoria: "mensagens",
    nome: "Video Colecao Aura",
    anuncio: "Ad 1 - Video Colecao Aura",
    campanha: "[Msg] [Colecao AURA] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Videos diversos",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 4319,
    impressoes: 8913,
    cliquesLink: 145,
    conversas: 18,
    investido: 295.87,
    ctr: 1.63,
    cpc: 2.04,
    custoConversa: 16.44,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-10-10",
    categoria: "mensagens",
    nome: "Carrossel 10/10",
    anuncio: "Ad 3 - Carrossel 10/10",
    campanha: "[New Collection] [Msg] [Frio] [Engaj. -> Wpp] [Abo] [St/Reels] - Vídeos e Carrosséis",
    tipo: "carrossel",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 6165,
    impressoes: 8346,
    cliquesLink: 82,
    conversas: 17,
    investido: 301.75,
    ctr: 0.98,
    cpc: 3.68,
    custoConversa: 17.75,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-08-10",
    categoria: "mensagens",
    nome: "Carrossel 08/10",
    anuncio: "Ad 4 - Carrossel 08/10",
    campanha: "[New Collection] [Msg] [Frio] [Engaj. -> Wpp] [Abo] [St/Reels] - Vídeos e Carrosséis",
    tipo: "carrossel",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 1155,
    impressoes: 1530,
    cliquesLink: 12,
    conversas: 4,
    investido: 76.04,
    ctr: 0.78,
    cpc: 6.34,
    custoConversa: 19.01,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DPkMLESjRGC/",
    instagramShortcode: "DPkMLESjRGC",
    thumbSrc: "/ads/mm-ig-DPkMLESjRGC.jpg",
  },
  {
    id: "msg-carrossel-feed-24-08",
    categoria: "mensagens",
    nome: "Carrossel Feed 24/08",
    anuncio: "Ad 4 - Carrossel Feed 24/08",
    campanha: "[Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 4169,
    impressoes: 7115,
    cliquesLink: 66,
    conversas: 10,
    investido: 192.03,
    ctr: 0.93,
    cpc: 2.91,
    custoConversa: 19.2,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DNwIfSCv6Pa/",
    instagramShortcode: "DNwIfSCv6Pa",
    thumbSrc: "/ads/mm-ig-DNwIfSCv6Pa.jpg",
  },
  {
    id: "msg-carrossel-unique-blue-03-10",
    categoria: "mensagens",
    nome: "Carrossel Unique Blue (03/10)",
    anuncio: "Ad 1 - Carrossel Unique Blue (03/10)",
    campanha: "[Msg] [Out/25] [Engaj. -> Wpp] [Funil Rmkt] [Abo] - Carrossel",
    tipo: "carrossel",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 4913,
    impressoes: 7721,
    cliquesLink: 41,
    conversas: 15,
    investido: 326.32,
    ctr: 0.53,
    cpc: 7.96,
    custoConversa: 21.75,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DPXarEcje8J/",
    instagramShortcode: "DPXarEcje8J",
    thumbSrc: "/ads/mm-ig-DPXarEcje8J.jpg",
  },
  {
    id: "msg-new-carrossel-17-11",
    categoria: "mensagens",
    nome: "New Carrossel (17/11)",
    anuncio: "Ad 1 - New Carrossel (17/11)",
    campanha: "[Msg] [New Collection] [Rmkt All] [3] [Engaj. -> Conversas Wpp] [Cbo] - Carrossel [2] - Novo 17/11",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 3329,
    impressoes: 6528,
    cliquesLink: 76,
    conversas: 9,
    investido: 210.49,
    ctr: 1.16,
    cpc: 2.77,
    custoConversa: 23.39,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DRLOBPADR_L/",
    instagramShortcode: "DRLOBPADR_L",
    thumbSrc: "/ads/mm-ig-DRLOBPADR_L.jpg",
  },
  {
    id: "msg-video-colecao-primavera",
    categoria: "mensagens",
    nome: "Video Colecao Primavera",
    anuncio: "Ad 0 - Video Colecao Primavera",
    campanha: "[Msg] [Frio] [Engaj. -> Wpp] [Cbo] - Video",
    tipo: "video",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 8697,
    impressoes: 16695,
    cliquesLink: 117,
    conversas: 44,
    investido: 1030.94,
    ctr: 0.7,
    cpc: 8.81,
    custoConversa: 23.43,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-reels-21-09",
    categoria: "mensagens",
    nome: "Video Reels 21/09",
    anuncio: "Ad 1 - Video Reels 21/09",
    campanha: "[Msg] [2] [Rmkt] [Engaj. -> Wpp] [Cbo] - Video",
    tipo: "reel",
    periodo: "Set–Out/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-10-31",
    alcance: 15091,
    impressoes: 55797,
    cliquesLink: 215,
    conversas: 61,
    investido: 1825.65,
    ctr: 0.39,
    cpc: 8.49,
    custoConversa: 29.93,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/reel/DO4Yyh1DVp-/",
    instagramShortcode: "DO4Yyh1DVp-",
    thumbSrc: "/ads/mm-ig-DO4Yyh1DVp-.jpg",
  },
  {
    id: "msg-carrossel-11-10-colecao-luz",
    categoria: "mensagens",
    nome: "Carrossel 11/10 (colecao luz)",
    anuncio: "Ad 2 - Carrossel 11/10 (colecao luz)",
    campanha: "[Msg] [Out/25] [Engaj. -> Wpp] [Funil Rmkt] [Abo] - Carrossel",
    tipo: "carrossel",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 2601,
    impressoes: 4028,
    cliquesLink: 15,
    conversas: 4,
    investido: 125.74,
    ctr: 0.37,
    cpc: 8.38,
    custoConversa: 31.44,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DPq4DYZjfrF/",
    instagramShortcode: "DPq4DYZjfrF",
    thumbSrc: "/ads/mm-ig-DPq4DYZjfrF.jpg",
  },
  {
    id: "msg-post-isadora-colar-stela",
    categoria: "mensagens",
    nome: "Post Isadora Colar Stela",
    anuncio: "Ad 1 - Post Isadora Colar Stela",
    campanha: "[Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] - Carrossel",
    tipo: "imagem",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 2276,
    impressoes: 7576,
    cliquesLink: 59,
    conversas: 11,
    investido: 368,
    ctr: 0.78,
    cpc: 6.24,
    custoConversa: 33.45,
    influenciador: "Isadora",
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-colecao-origem",
    categoria: "mensagens",
    nome: "Carrossel Coleção Origem",
    anuncio: "Ad 1 - Carrossel Coleção Origem",
    campanha: "[New Collection] [Msg] [Frio] [Engaj. -> Wpp] [Abo] [St/Reels] - Vídeos e Carrosséis",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 506,
    impressoes: 587,
    cliquesLink: 4,
    conversas: 1,
    investido: 33.82,
    ctr: 0.68,
    cpc: 8.46,
    custoConversa: 33.82,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-new-collection",
    categoria: "mensagens",
    nome: "Carrossel New Collection",
    anuncio: "Ad 0 - Carrossel New Collection",
    campanha: "[New Collection] [Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] [St] - Carrossel St",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 1691,
    impressoes: 3960,
    cliquesLink: 30,
    conversas: 7,
    investido: 247.86,
    ctr: 0.76,
    cpc: 8.26,
    custoConversa: 35.41,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-new-collection-origem",
    categoria: "mensagens",
    nome: "Video New Collection (origem)",
    anuncio: "Ad 0 - Video New Collection (origem)",
    campanha: "[New Collection] [Msg] [Frio] [Engaj. -> Wpp] [Abo] [St/Reels] - Vídeos e Carrosséis",
    tipo: "video",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 7995,
    impressoes: 15042,
    cliquesLink: 80,
    conversas: 17,
    investido: 608.33,
    ctr: 0.53,
    cpc: 7.6,
    custoConversa: 35.78,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-diamonds-01-10",
    categoria: "mensagens",
    nome: "Carrossel Diamonds (01/10)",
    anuncio: "Ad 0 - Carrossel Diamonds (01/10)",
    campanha: "[Msg] [Out/25] [Engaj. -> Wpp] [Funil Rmkt] [Abo] - Carrossel",
    tipo: "carrossel",
    periodo: "Out/2025",
    inicioRelatorio: "2025-10-01",
    fimRelatorio: "2025-10-31",
    alcance: 7750,
    impressoes: 14901,
    cliquesLink: 68,
    conversas: 10,
    investido: 467.34,
    ctr: 0.46,
    cpc: 6.87,
    custoConversa: 46.73,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DPSOZssjWPc/",
    instagramShortcode: "DPSOZssjWPc",
    thumbSrc: "/ads/mm-ig-DPSOZssjWPc.jpg",
  },
  {
    id: "msg-post-carrossel-09-08-colecao-luz",
    categoria: "mensagens",
    nome: "Post Carrossel 09/08 (colecao luz)",
    anuncio: "Ad 0 - Post Carrossel 09/08 (colecao luz)",
    campanha: "[Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Ago/2025",
    inicioRelatorio: "2025-08-01",
    fimRelatorio: "2025-08-31",
    alcance: 2239,
    impressoes: 4452,
    cliquesLink: 43,
    conversas: 3,
    investido: 235.29,
    ctr: 0.97,
    cpc: 5.47,
    custoConversa: 78.43,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DNJFHcJs5kQ/",
    instagramShortcode: "DNJFHcJs5kQ",
    thumbSrc: "/ads/mm-ig-DNJFHcJs5kQ.jpg",
  },
  {
    id: "msg-carrossel-feed-26-08",
    categoria: "mensagens",
    nome: "Carrossel Feed 26/08",
    anuncio: "Ad 3 - Carrossel Feed 26/08",
    campanha: "[Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Set/2025",
    inicioRelatorio: "2025-09-01",
    fimRelatorio: "2025-09-30",
    alcance: 2284,
    impressoes: 3230,
    cliquesLink: 25,
    conversas: 1,
    investido: 103.18,
    ctr: 0.77,
    cpc: 4.13,
    custoConversa: 103.18,
    influenciador: null,
    instagramUrl: "https://www.instagram.com/p/DNokauuvn8-/",
    instagramShortcode: "DNokauuvn8-",
    thumbSrc: "/ads/mm-ig-DNokauuvn8-.jpg",
  },
  {
    id: "msg-video-new-collection-shop-now",
    categoria: "mensagens",
    nome: "Vídeo New Collection \"shop now\"",
    anuncio: "Ad 0 - Vídeo New Collection \"shop now\"",
    campanha: "[Msg] [New Collection] [2] [Rmkt All] [Engaj. -> Conversas Wpp] [Cbo] - Vídeo",
    tipo: "video",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 2808,
    impressoes: 6893,
    cliquesLink: 61,
    conversas: 2,
    investido: 224.44,
    ctr: 0.88,
    cpc: 3.68,
    custoConversa: 112.22,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-mm-diamonds-presentes",
    categoria: "mensagens",
    nome: "Carrossel MM Diamonds - Presentes",
    anuncio: "Ad 3 - Carrossel MM Diamonds - Presentes",
    campanha: "[Msg] [Especial Presentes] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Carrossel",
    tipo: "carrossel",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 524,
    impressoes: 616,
    cliquesLink: 4,
    conversas: 0,
    investido: 13.37,
    ctr: 0.65,
    cpc: 3.34,
    custoConversa: null,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-video-mm-diamonds-edicao-especial",
    categoria: "mensagens",
    nome: "Vídeo MM Diamonds - Edicao Especial",
    anuncio: "Ad 4 - Vídeo MM Diamonds - Edicao Especial",
    campanha: "[Msg] [Especial Presentes] [2] [Rmkt All]  [Engaj. -> Conversas Wpp] [Cbo] - Vídeos",
    tipo: "video",
    periodo: "Dez/2025",
    inicioRelatorio: "2025-12-01",
    fimRelatorio: "2025-12-26",
    alcance: 81,
    impressoes: 99,
    cliquesLink: 0,
    conversas: 0,
    investido: 1.09,
    ctr: 0,
    cpc: null,
    custoConversa: null,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-origem-post-nos-stories-2",
    categoria: "mensagens",
    nome: "Carrossel Origem (post nos stories) [2]",
    anuncio: "Ad 1 - Carrossel Origem (post nos stories) [2]",
    campanha: "[New Collection] [Msg] [Rmkt] [2] [Engaj. -> Wpp] [Cbo] [St] - Carrossel St",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 62,
    impressoes: 82,
    cliquesLink: 0,
    conversas: 0,
    investido: 3.26,
    ctr: 0,
    cpc: null,
    custoConversa: null,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
  {
    id: "msg-carrossel-new-collection-cards-video",
    categoria: "mensagens",
    nome: "Carrossel New Collection [Cards + Video]",
    anuncio: "Ad 1 - Carrossel New Collection [Cards + Video]",
    campanha: "[New Collection] [Msg] [Rmkt] [Engaj. -> Wpp] [Cbo] [St] - Carrossel St",
    tipo: "carrossel",
    periodo: "Nov/2025",
    inicioRelatorio: "2025-11-01",
    fimRelatorio: "2025-11-30",
    alcance: 64,
    impressoes: 76,
    cliquesLink: 0,
    conversas: 0,
    investido: 5.03,
    ctr: 0,
    cpc: null,
    custoConversa: null,
    influenciador: null,
    instagramUrl: null,
    instagramShortcode: null,
    thumbSrc: null,
  },
] as const;

